DELIMITER //
CREATE PROCEDURE putAlumno 
(
    IN DNI_ALUMNO VARCHAR(9),
    IN NOMBRE_ALUMNO VARCHAR(20),
    IN APELLIDOS_ALUMNO VARCHAR(50),
    IN EMAIL_ALUMNO VARCHAR(30)
)
BEGIN 
IF NOT EXISTS 
(
    SELECT * FROM Alumno WHERE DNI = DNI_ALUMNO
)
THEN
INSERT INTO Alumno
VALUES 
(
    null,
    DNI_ALUMNO,
    NOMBRE_ALUMNO,
    APELLIDOS_ALUMNO,
    EMAIL_ALUMNO
);
ELSE
UPDATE Alumno
SET 
    Nombre = NOMBRE_ALUMNO,
    Apellidos = APELLIDOS_ALUMNO,
    email = EMAIL_ALUMNO
WHERE DNI = DNI_ALUMNO
;
END IF;
END //
DELIMITER ;