DELIMITER //
CREATE PROCEDURE putAsignatura 
(
    IN NOMBRE_ASIGNATURA VARCHAR(60),
    IN CICLO_ASIGNATURA VARCHAR(60),
    IN CURSO_ASIGNATURA VARCHAR(10),
    IN HORAS_ASIGNATURA INT
)
BEGIN 
IF NOT EXISTS 
(
    SELECT * FROM Asignatura WHERE Nombre = NOMBRE_ASIGNATURA
)
THEN
INSERT INTO Asignatura
VALUES 
(
    null,
    NOMBRE_ASIGNATURA,
    CICLO_ASIGNATURA,
    CURSO_ASIGNATURA,
    HORAS_ASIGNATURA
);
ELSE
UPDATE Asignatura
SET 
    Nombre = NOMBRE_ASIGNATURA,
    Ciclo = CICLO_ASIGNATURA,
    Curso = CURSO_ASIGNATURA,
    Horas = HORAS_ASIGNATURA
WHERE Nombre = NOMBRE_ASIGNATURA
;
END IF;
END //
DELIMITER ;